const imgs = {
    f1: require('../../assets/CouncilPage2/Mrs. Mona_Deshmukh.jpg').default,
    f2: require('../../assets/CouncilPage2/Mrs. Charusheela_Nehete.jpg').default,

    be1:  require('../../assets/CouncilPage2/2022_BE/Fayzaan_Qureshi.jpg').default,
    be2:  require('../../assets/CouncilPage2/2022_BE/Saurav_Telge.jpeg').default,
    be3:  require('../../assets/CouncilPage2/2022_BE/Shreya_Shah.jpg').default,
    be4:  require('../../assets/CouncilPage2/2022_BE/Saloni_Ingle.jpg').default,
    be5:  require('../../assets/CouncilPage2/2022_BE/Pooja_Prasad.jpg').default,
    be6:  require('../../assets/CouncilPage2/2022_BE/Abhishek_Joshi.jpg').default,
    be7:  require('../../assets/CouncilPage2/2022_BE/Adarsh_Raut.png').default,
    be8:  require('../../assets/CouncilPage2/2022_BE/Anmol_Devnani.jpg').default,
    be9:  require('../../assets/CouncilPage2/2022_BE/Arya_Paryani.jpg').default,
    be10: require('../../assets/CouncilPage2/2022_BE/Bhavesh_Lohana.jpg').default,
    be11: require('../../assets/CouncilPage2/2022_BE/Etisha_Mathurvaishya.jpg').default,
    be12: require('../../assets/CouncilPage2/2022_BE/Kevin_Abraham.jpg').default,
    be13: require('../../assets/CouncilPage2/2022_BE/Mahek_Nagdev.jpg').default,
    be14: require('../../assets/CouncilPage2/2022_BE/Nagesh_Nayak.jpeg').default,
    be15: require('../../assets/CouncilPage2/2022_BE/Pooja_Koshti.jpg').default,
    be16: require('../../assets/CouncilPage2/2022_BE/Pratik_Dubey.jpg').default,
    be17: require('../../assets/CouncilPage2/2022_BE/Sadhvi_Ganuwala.jpg').default,
    be18: require('../../assets/CouncilPage2/2022_BE/SherAli_Shaikh.jpg').default,
    be19: require('../../assets/CouncilPage2/2022_BE/Swarangi_Dali.png').default,
    be20: require('../../assets/CouncilPage2/2022_BE/Vedant_Sawant.jpg').default,
    be21: require('../../assets/CouncilPage2/2022_BE/Yash_Wadhwani.jpg').default,

    te1: require('../../assets/CouncilPage2/2022_TE/Adarsh_Kadam.jpeg').default,
    te2: require('../../assets/CouncilPage2/2022_TE/Aditya_Dubey.jpg').default,
    te3: require('../../assets/CouncilPage2/2022_TE/Akhil_Chakkungal.jpeg').default,
    te4: require('../../assets/CouncilPage2/2022_TE/Aniket_Devnani.jpeg').default,
    te5: require('../../assets/CouncilPage2/2022_TE/Ashish_Shingade.jpeg').default,

    te6: require('../../assets/CouncilPage2/2022_TE/Drishti_Katiyara.jpg').default,
    te7: require('../../assets/CouncilPage2/2022_TE/Harsh_Bhat.jpg').default,
    te8: require('../../assets/CouncilPage2/2022_TE/Jahnavi_Mulchandani.jpg').default,
    te9: require('../../assets/CouncilPage2/2022_TE/Mcvean_Soans.jpg').default,
    te10: require('../../assets/CouncilPage2/2022_TE/Meet_Patel.jpg').default,
    te11: require('../../assets/CouncilPage2/2022_TE/Mihir_Rane.jpg').default,
    te12: require('../../assets/CouncilPage2/2022_TE/Mugdha_Sholapure.jpg').default,
    te13: require('../../assets/CouncilPage2/2022_TE/Neeharika_Nagori.jpg').default,
    te14: require('../../assets/CouncilPage2/2022_TE/Nupur_Jeswani.jpeg').default,
    te15: require('../../assets/CouncilPage2/2022_TE/Pratik_Vartak.jpeg').default,
    te16: require('../../assets/CouncilPage2/2022_TE/Rohan_Padhye.jpg').default,
    te17: require('../../assets/CouncilPage2/2022_TE/Roshni_Jha.jpg').default,
    te18: require('../../assets/CouncilPage2/2022_TE/Shreyas_Poojari.jpg').default,
    te19: require('../../assets/CouncilPage2/2022_TE/Sristi_Sharma.jpg').default,
    te20: require('../../assets/CouncilPage2/2022_TE/Vanshika_Bajaj.jpg').default,
}
export default imgs;