const imgs = {
    f1: require('../../assets/CouncilPage/Mrs.Mona_Deshmukh-rmbg.png').default,
    f2: require('../../assets/CouncilPage/Mrs.Charusheela_Nehete-rmbg.png').default,

    be1:  require('../../assets/CouncilPage/2022_BE/Fayzaan_Qureshi-rmbg.png').default,
    be2:  require('../../assets/CouncilPage/2022_BE/Saurav_Telge-rmbg.png').default,
    be3:  require('../../assets/CouncilPage/2022_BE/Shreya_Shah-rmbg.png').default,
    be4:  require('../../assets/CouncilPage/2022_BE/Saloni_Ingle-rmbg.png').default,
    be5:  require('../../assets/CouncilPage/2022_BE/Pooja_Prasad-rmbg.png').default,
    be6:  require('../../assets/CouncilPage/2022_BE/Abhishek_Joshi-rmbg.png').default,
    be7:  require('../../assets/CouncilPage/2022_BE/Adarsh_Raut-rmbg.png').default,
    be8:  require('../../assets/CouncilPage/2022_BE/Anmol_Devnani-rmbg.png').default,
    be9:  require('../../assets/CouncilPage/2022_BE/Arya_Paryani-rmbg.png').default,
    be10: require('../../assets/CouncilPage/2022_BE/Bhavesh_Lohana-rmbg.png').default,
    be11: require('../../assets/CouncilPage/2022_BE/Etisha_Mathurvaishya-rmbg.png').default,
    be12: require('../../assets/CouncilPage/2022_BE/Kevin_Abraham-rmbg.png').default,
    be13: require('../../assets/CouncilPage/2022_BE/Mahek_Nagdev-rmbg.png').default,
    be14: require('../../assets/CouncilPage/2022_BE/Nagesh-rmbg.png').default,
    be15: require('../../assets/CouncilPage/2022_BE/Pooja_Koshti-rmbg.png').default,
    be16: require('../../assets/CouncilPage/2022_BE/Pratik_Dubey-rmbg.png').default,
    be17: require('../../assets/CouncilPage/2022_BE/Sadhvi_Ganuwala-rmbg.png').default,
    be18: require('../../assets/CouncilPage/2022_BE/SherAli_Shaikh-rmbg.png').default,
    be19: require('../../assets/CouncilPage/2022_BE/Swarangi_Dali-tmbg.png').default,
    be20: require('../../assets/CouncilPage/2022_BE/Vedant_Sawant-rmbg.png').default,
    be21: require('../../assets/CouncilPage/2022_BE/Yash-removebg-preview.png').default,

    te1: require('../../assets/CouncilPage/2022_TE/Adarsh_Kadam-rmbg.png').default,
    te2: require('../../assets/CouncilPage/2022_TE/Aditya_Dubey-rmbg.png').default,
    te3: require('../../assets/CouncilPage/2022_TE/Akhil_Chakkungal-rmbg.png').default,
    te4: require('../../assets/CouncilPage/2022_TE/Aniket_Dewnani-rmbg.png').default,
    te5: require('../../assets/CouncilPage/2022_TE/Ashish_Shingade-rmbg.png').default,

    te6: require('../../assets/CouncilPage/2022_TE/Drishti_Katiyara-rmbg.png').default,
    te7: require('../../assets/CouncilPage/2022_TE/Harsh_Bhat-rmbg.png').default,
    te8: require('../../assets/CouncilPage/2022_TE/Jahnavi_Mulchandani-rmbg.png').default,
    te9: require('../../assets/CouncilPage/2022_TE/Mcvean_Soans-rmbg.png').default,
    te10: require('../../assets/CouncilPage/2022_TE/Meet_Patel-rmbg.png').default,
    te11: require('../../assets/CouncilPage/2022_TE/Mihir_Rane-rmbg.png').default,
    te12: require('../../assets/CouncilPage/2022_TE/Mugdha_Sholapure-rmbg.png').default,
    te13: require('../../assets/CouncilPage/2022_TE/Neeharika_Nagori-rmbg.png').default,
    te14: require('../../assets/CouncilPage/2022_TE/Nupur_Jeswani-rmbg.png').default,
    te15: require('../../assets/CouncilPage/2022_TE/Pratik_Vartak-rmbg.png').default,
    te16: require('../../assets/CouncilPage/2022_TE/Rohan_Padhye-rmbg.png').default,
    te17: require('../../assets/CouncilPage/2022_TE/Roshni_Jha-rmbg.png').default,
    te18: require('../../assets/CouncilPage/2022_TE/Shreyas_Poojari-rmbg.png').default,
    te19: require('../../assets/CouncilPage/2022_TE/Sristi_Sharma-rmbg.png').default,
    te20: require('../../assets/CouncilPage/2022_TE/Vanshika_Bajaj-rmbg.png').default,
}
export default imgs;